import {LayoutProps} from "./Layout.props";
import {Footer, Header} from "../index";
import styles from "./Layout.module.scss";
import Head from "next/head";

export const Layout = ({ children }: LayoutProps) => {
    return (
        <>
            <Head>
                <title>Movies List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
            </Head>
            <div className={styles.layout}>
                <Header className={styles.layoutHeader} />
                <main className={styles.layoutMain}>
                    {children}
                </main>
                <Footer className={styles.layoutFooter} />
            </div>
        </>
    )
}