import Head from "next/head";
import styles from "./Homepage.module.scss";
import Link from "next/link";

export const Homepage = () => {
    return (
        <>
            <Head>
                <title>Movies List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.home}>
                <h1 className={styles.homeTitle}>Movies List</h1>
                <p className={styles.homeOffer}>Найдется фильм на любой вкус</p>
                <Link href='/films'><a className={styles.homeLink}>Искать фильмы</a></Link>
            </section>

        </>
    )
}