import Head from "next/head";

export const Homepage = () => {
    return (
        <>
            <Head>
                <title>Movies List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            HomePage
        </>
    )
}